const questionsData = [
    // 1–10
    {
        question: "Which company developed JavaScript?",
        options: ["Microsoft", "Netscape", "Google", "Oracle"],
        correctOption: 1,
        hint: "Created during the early browser era.",
    },
    {
        question: "Which keyword is used to declare a variable in JavaScript?",
        options: ["var", "let", "const", "All of the above"],
        correctOption: 3,
        hint: "JS supports multiple declaration styles.",
    },
    {
        question: "What is the output of typeof null?",
        options: ["null", "object", "undefined", "number"],
        correctOption: 1,
        hint: "A long-standing JavaScript oddity.",
    },
    {
        question: "Which method converts JSON question to a JavaScript object?",
        options: [
            "JSON.parse()",
            "JSON.stringify()",
            "JSON.convert()",
            "JSON.toObj()",
        ],
        correctOption: 0,
        hint: "Used when reading JSON data.",
    },
    {
        question: "How do you write a single-line comment in JS?",
        options: ["<!-- -->", "//", "/*", "**"],
        correctOption: 1,
        hint: "Common syntax in many languages.",
    },
    {
        question: "Which operator is used to compare both value and type?",
        options: ["==", "===", "!=", "!="],
        correctOption: 1,
        hint: "Used for strict comparison.",
    },
    {
        question: "Which of these is NOT a JavaScript data type?",
        options: ["Number", "String", "Character", "Boolean"],
        correctOption: 2,
        hint: "JS does not separate single letters.",
    },
    {
        question: "Which keyword stops a loop?",
        options: ["stop", "halt", "break", "exit"],
        correctOption: 2,
        hint: "Also ends switch cases.",
    },
    {
        question: "What is the default value of an uninitialized variable?",
        options: ["null", "0", "undefined", "empty string"],
        correctOption: 2,
        hint: "Indicates 'not assigned yet'.",
    },
    {
        question: "Which symbol is used for strict equality?",
        options: ["==", "===", "=", "!=="],
        correctOption: 1,
        hint: "Stricter version of double equals.",
    },

    // 11–20
    {
        question: "Which method adds an item to the end of an array?",
        options: ["push()", "pop()", "shift()", "unshift()"],
        correctOption: 0,
        hint: "Opposite of removing from the end.",
    },
    {
        question: "What does DOM stand for?",
        options: [
            "Data Object Model",
            "Document Object Model",
            "Digital Ordinance Model",
            "Document Order Mode",
        ],
        correctOption: 1,
        hint: "Represents webpage structure.",
    },
    {
        question: "Which loop runs at least once?",
        options: ["for", "while", "do...while", "foreach"],
        correctOption: 2,
        hint: "Condition checked after running.",
    },
    {
        question: "Which keyword declares a constant?",
        options: ["constant", "final", "const", "let"],
        correctOption: 2,
        hint: "Used for fixed values.",
    },
    {
        question: "Which function is used to print something in the console?",
        options: ["print()", "echo()", "console.log()", "write()"],
        correctOption: 2,
        hint: "Used often in debugging.",
    },
    {
        question: "What will '3' + 2 return?",
        options: ["5", "32", "NaN", "undefined"],
        correctOption: 1,
        hint: "String wins in this case.",
    },
    {
        question: "What will 3 - '2' return?",
        options: ["NaN", "32", "1", "undefined"],
        correctOption: 2,
        hint: "Math forces conversion.",
    },
    {
        question: "What does NaN stand for?",
        options: [
            "Not a Number",
            "No any Number",
            "Not a Name",
            "Negative and Null",
        ],
        correctOption: 0,
        hint: "Appears when math fails.",
    },
    {
        question: "Which method removes the last element from an array?",
        options: ["shift()", "pop()", "unshift()", "remove()"],
        correctOption: 1,
        hint: "Opposite of adding to the end.",
    },
    {
        question: "Which method converts an array to a string?",
        options: ["join()", "toString()", "Both", "None"],
        correctOption: 2,
        hint: "More than one method does this.",
    },

    // 21–30
    {
        question: "How do you write a multi-line comment?",
        options: [
            "// comment //",
            "<!-- comment -->",
            "/* comment */",
            "** comment **",
        ],
        correctOption: 2,
        hint: "Common in C-style languages.",
    },
    {
        question: "Which keyword defines a class?",
        options: ["class", "function", "object", "define"],
        correctOption: 0,
        hint: "Same in most OOP languages.",
    },
    {
        question: "Inside which HTML tag is JS written?",
        options: ["<javascript>", "<script>", "<js>", "<code>"],
        correctOption: 1,
        hint: "A short, simple HTML tag.",
    },
    {
        question: "Which event fires when a button is clicked?",
        options: ["onhover", "onclick", "onpress", "onchange"],
        correctOption: 1,
        hint: "Triggers on user interaction.",
    },
    {
        question: "Which operator checks value only?",
        options: ["==", "===", "!=", "!=="],
        correctOption: 0,
        hint: "Allows type conversion.",
    },
    {
        question: "How do you declare an arrow function?",
        options: ["function => {}", "() => {}", "(=>) {}", "lambda()"],
        correctOption: 1,
        hint: "Uses an arrow symbol.",
    },
    {
        question: "Which method removes the first array element?",
        options: ["shift()", "pop()", "unshift()", "remove()"],
        correctOption: 0,
        hint: "Opposite of adding at the beginning.",
    },
    {
        question: "Which built-in method sorts an array?",
        options: ["sort()", "order()", "list()", "arrange()"],
        correctOption: 0,
        hint: "Can change original array.",
    },
    {
        question: "Which is a primitive type?",
        options: ["Object", "Array", "Undefined", "Function"],
        correctOption: 2,
        hint: "Represents absence of a value.",
    },
    {
        question: "Which operator is used for OR?",
        options: ["&&", "||", "&", "!"],
        correctOption: 1,
        hint: "Two identical symbols.",
    },

    // 31–40
    {
        question: "What is the output of 2 + true?",
        options: ["3", "2true", "NaN", "undefined"],
        correctOption: 0,
        hint: "true acts like a small number.",
    },
    {
        question: "Which method returns the length of a string?",
        options: ["length()", "count()", "size()", "length"],
        correctOption: 3,
        hint: "It's a property, not a function.",
    },
    {
        question: "Which symbol starts a template literal?",
        options: ['"', "'", "`", "~"],
        correctOption: 2,
        hint: "Used for multiline strings.",
    },
    {
        question: "What will Boolean(0) return?",
        options: ["true", "false", "null", "undefined"],
        correctOption: 1,
        hint: "Zero is one of the special values.",
    },
    {
        question: "How do you convert a string to a number?",
        options: ["Number()", "parseInt()", "parseFloat()", "All of these"],
        correctOption: 3,
        hint: "Several built-ins can do this.",
    },
    {
        question: "Which method adds an element at the beginning of an array?",
        options: ["push()", "attach()", "start()", "unshift()"],
        correctOption: 3,
        hint: "Opposite of removing from front.",
    },
    {
        question: "Which object deals with page alerts?",
        options: ["window", "document", "alert", "browser"],
        correctOption: 0,
        hint: "Top-level browser object.",
    },
    {
        question: "Which object represents the whole HTML page?",
        options: ["window", "document", "page", "body"],
        correctOption: 1,
        hint: "Root of DOM access.",
    },
    {
        question: "Which method checks if an array contains a value?",
        options: ["includes()", "has()", "contains()", "inArray()"],
        correctOption: 0,
        hint: "Returns true/false.",
    },
    {
        question: "What will NaN === NaN return?",
        options: ["true", "false", "undefined", "error"],
        correctOption: 1,
        hint: "This value behaves uniquely.",
    },

    // 41–50
    {
        question: "What is the output of [] == []?",
        options: ["true", "false", "undefined", "error"],
        correctOption: 1,
        hint: "Two separate objects never match.",
    },
    {
        question: "Which built-in method returns index of a value?",
        options: ["indexOf()", "find()", "locate()", "search()"],
        correctOption: 0,
        hint: "Common in strings too.",
    },
    {
        question: "Which method converts a number to string?",
        options: ["toString()", "stringify()", "convert()", "str()"],
        correctOption: 0,
        hint: "Most JS types use this.",
    },
    {
        question: "How do you define a class constructor?",
        options: ["make()", "constructor()", "__init__", "create()"],
        correctOption: 1,
        hint: "Special method for initialization.",
    },
    {
        question: "What is the output of typeof []?",
        options: ["object", "array", "list", "undefined"],
        correctOption: 0,
        hint: "Arrays don't have their own typeof type.",
    },
    {
        question: "Which loop is used for arrays?",
        options: ["for", "while", "for...of", "loop array"],
        correctOption: 2,
        hint: "Best for iterating values directly.",
    },
    {
        question: "What does break do?",
        options: [
            "Skips iteration",
            "Stops loop",
            "Repeats loop",
            "Restarts loop",
        ],
        correctOption: 1,
        hint: "Ends the current loop.",
    },
    {
        question: "What will 10 % 3 return?",
        options: ["1", "3", "10", "0"],
        correctOption: 0,
        hint: "Represents the leftover.",
    },
    {
        question: "Which operator is used for AND?",
        options: ["&&", "||", "&", "!"],
        correctOption: 0,
        hint: "Two characters used together.",
    },
    {
        question: "Which function displays a popup?",
        options: ["print()", "log()", "alert()", "popup()"],
        correctOption: 2,
        hint: "Simple browser message box.",
    },

    // 51–60
    {
        question: "Which method repeats a string?",
        options: ["duplicate()", "repeat()", "copy()", "clone()"],
        correctOption: 1,
        hint: "Useful for pattern creation.",
    },
    {
        question: "Which statement defines a function?",
        options: [
            "function myFun() {}",
            "func myFun {}",
            "def myFun()",
            "fun = {}",
        ],
        correctOption: 0,
        hint: "Classic JS syntax.",
    },
    {
        question: "What is closure?",
        options: [
            "A function inside a string",
            "A function with access to its parents' scope",
            "A variable",
            "An array inside a function",
        ],
        correctOption: 1,
        hint: "Related to lexical scoping.",
    },
    {
        question: "What is typeof []?",
        options: ["array", "object", "list", "undefined"],
        correctOption: 1,
        hint: "Arrays don't get their own typeof type.",
    },
    {
        question: "Which method merges arrays?",
        options: ["concat()", "combine()", "merge()", "append()"],
        correctOption: 0,
        hint: "Does not change original arrays.",
    },
    {
        question: "How do you round a number?",
        options: ["Math.round()", "round()", "Math.floor()", "approx()"],
        correctOption: 0,
        hint: "A Math method handles this.",
    },
    {
        question: "Which object handles time?",
        options: ["Date", "Time", "Clock", "Timer"],
        correctOption: 0,
        hint: "Built-in for timestamps.",
    },
    {
        question: "Which operator is used to spread arrays?",
        options: ["...", "++", "**", "&&"],
        correctOption: 0,
        hint: "Looks like three dots.",
    },
    {
        question: "What is the output of '5' - 2?",
        options: ["3", "52", "NaN", "undefined"],
        correctOption: 0,
        hint: "Subtraction forces conversion.",
    },
    {
        question: "Which operator is used for NOT?",
        options: ["!", "not", "~", "#"],
        correctOption: 0,
        hint: "Used in logical negation.",
    },

    // 61–70
    {
        question: "Which method returns a sliced part of string?",
        options: ["slice()", "splice()", "cut()", "split()"],
        correctOption: 0,
        hint: "Works for arrays too.",
    },
    {
        question: "What does array.length return?",
        options: [
            "Last index",
            "Total elements",
            "Empty elements",
            "Undefined",
        ],
        correctOption: 1,
        hint: "Counts items inside.",
    },
    {
        question: "Which method removes spaces?",
        options: ["remove()", "trim()", "cut()", "strip()"],
        correctOption: 1,
        hint: "Useful for cleaning input.",
    },
    {
        question: "Which function parses float?",
        options: ["parseInt()", "parseFloat()", "float()", "Number()"],
        correctOption: 1,
        hint: "Used for decimals.",
    },
    {
        question: "What is the output of Boolean('')?",
        options: ["true", "false", "undefined", "NaN"],
        correctOption: 1,
        hint: "Empty values act falsy.",
    },
    {
        question: "Which operator adds strings?",
        options: ["+", "-", "*", "="],
        correctOption: 0,
        hint: "Same operator used in arithmetic.",
    },
    {
        question: "Which method finds the first matching element?",
        options: ["find()", "filter()", "map()", "reduce()"],
        correctOption: 0,
        hint: "Returns a single value.",
    },
    {
        question: "Which method transforms each array element?",
        options: ["filter()", "map()", "reduce()", "forEach()"],
        correctOption: 1,
        hint: "Creates a new array.",
    },
    {
        question: "Which method filters an array?",
        options: ["map()", "filter()", "reduce()", "find()"],
        correctOption: 1,
        hint: "Used to keep matching items.",
    },
    {
        question: "Which method is used for reducing array values?",
        options: ["reduce()", "map()", "filter()", "slice()"],
        correctOption: 0,
        hint: "Useful for totals.",
    },

    // 71–80
    {
        question: "Which of the following is falsy?",
        options: ["0", "''", "null", "All of them"],
        correctOption: 3,
        hint: "Several values behave as false.",
    },
    {
        question: "Which method replaces part of a string?",
        options: ["replace()", "switch()", "swap()", "change()"],
        correctOption: 0,
        hint: "Useful for modifying question.",
    },
    {
        question: "What is the output of typeof function(){}?",
        options: ["object", "function", "method", "undefined"],
        correctOption: 1,
        hint: "Functions have a unique typeof.",
    },
    {
        question: "Which operator is used for exponent?",
        options: ["^", "**", "^^", "//"],
        correctOption: 1,
        hint: "Two identical symbols.",
    },
    {
        question: "What will null == undefined return?",
        options: ["true", "false", "NaN", "error"],
        correctOption: 0,
        hint: "These two are loosely related.",
    },
    {
        question: "Which method converts string to lowercase?",
        options: ["toLower()", "lower()", "toLowerCase()", "small()"],
        correctOption: 2,
        hint: "Has 'Case' in its name.",
    },
    {
        question: "Which removes multiple items from array?",
        options: ["slice()", "splice()", "cut()", "remove()"],
        correctOption: 1,
        hint: "Able to remove and insert.",
    },
    {
        question: "Which returns true/false for every element?",
        options: ["every()", "some()", "filter()", "map()"],
        correctOption: 0,
        hint: "Checks all items.",
    },
    {
        question: "Which checks if at least one element matches?",
        options: ["every()", "some()", "contains()", "match()"],
        correctOption: 1,
        hint: "Needs only one match.",
    },
    {
        question: "Which method splits a string?",
        options: ["cut()", "slice()", "split()", "divide()"],
        correctOption: 2,
        hint: "Returns an array of parts.",
    },

    // 81–90
    {
        question: "What will '10' == 10 return?",
        options: ["true", "false", "NaN", "undefined"],
        correctOption: 0,
        hint: "Allows type coercion.",
    },
    {
        question: "What will '10' === 10 return?",
        options: ["true", "false", "NaN", "undefined"],
        correctOption: 1,
        hint: "Strict comparison matters here.",
    },
    {
        question: "Which method converts number to fixed decimals?",
        options: ["decimal()", "fix()", "toFixed()", "limit()"],
        correctOption: 2,
        hint: "Great for formatting values.",
    },
    {
        question: "What will [1,2] + [3,4] return?",
        options: ["[1,2,3,4]", "1,23,4", "1,23,4", "Error"],
        correctOption: 2,
        hint: "Arrays turn into strings in this case.",
    },
    {
        question: "Which method checks if value is number?",
        options: ["isNaN()", "Number.isNaN()", "isNumber()", "check()"],
        correctOption: 1,
        hint: "The strict version avoids coercion.",
    },
    {
        question: "What is event bubbling?",
        options: [
            "Event moves down",
            "Event moves up the DOM tree",
            "Event repeats",
            "Event loops infinitely",
        ],
        correctOption: 1,
        hint: "Moves through parent elements.",
    },
    {
        question: "Which removes event listener?",
        options: [
            "remove()",
            "removeEvent()",
            "removeEventListener()",
            "stopEvent()",
        ],
        correctOption: 2,
        hint: "Reverse of adding one.",
    },
    {
        question: "Which is not a loop?",
        options: ["for", "while", "foreach", "loop"],
        correctOption: 3,
        hint: "Not an actual JS keyword.",
    },
    {
        question: "Which keyword handles exceptions?",
        options: ["try", "catch", "finally", "All of them"],
        correctOption: 3,
        hint: "They work together in error handling.",
    },
    {
        question: "Which block always runs?",
        options: ["try", "catch", "finally", "none"],
        correctOption: 2,
        hint: "Executes regardless of errors.",
    },

    // 91–100
    {
        question: "Which API stores key-value pairs in browser?",
        options: ["localStorage", "cookies", "sessionStorage", "database"],
        correctOption: 0,
        hint: "Persistent across sessions.",
    },
    {
        question: "Which storage clears when tab is closed?",
        options: ["localStorage", "sessionStorage", "cookies", "cache"],
        correctOption: 1,
        hint: "Short-lived storage.",
    },
    {
        question: "Which converts JS object to JSON string?",
        options: [
            "JSON.parse()",
            "JSON.stringify()",
            "JSON.toString()",
            "JSON.export()",
        ],
        correctOption: 1,
        hint: "Opposite of parsing.",
    },
    {
        question: "Which method attaches an event?",
        options: ["addEvent()", "listen()", "addEventListener()", "on()"],
        correctOption: 2,
        hint: "Standard event binding method.",
    },
    {
        question: "Which returns today's date?",
        options: ["new Date()", "Date.today()", "Date()", "now()"],
        correctOption: 0,
        hint: "Creates a Date object.",
    },
    {
        question: "What is hoisting?",
        options: [
            "Moving vars to bottom",
            "Moving declarations to top",
            "Removing unused variables",
            "Inlining functions",
        ],
        correctOption: 1,
        hint: "JS handles declarations early.",
    },
    {
        question: "Which operator checks if a property exists?",
        options: ["in", "has", "contains", "exists"],
        correctOption: 0,
        hint: "Commonly used with objects.",
    },
    {
        question: "Which error type occurs in try/catch?",
        options: [
            "Syntax Error",
            "Runtime Error",
            "Logic Error",
            "Compile Error",
        ],
        correctOption: 1,
        hint: "Happens while executing code.",
    },
    {
        question: "Which timer repeats execution?",
        options: ["setTimeout()", "setInterval()", "repeat()", "loop()"],
        correctOption: 1,
        hint: "Runs repeatedly over time.",
    },
    {
        question: "Which stops interval?",
        options: ["stop()", "clearInterval()", "cancel()", "end()"],
        correctOption: 1,
        hint: "Used to stop a repeating timer.",
    },
];
